base_config: concat_loc_cambridge_oldhospital_processed_locguided_dcff_highres_depthaware_v17_selfmap_export_corrwls_probe_extproj_scale025.yaml
exp_name: concat_loc_cambridge_oldhospital_processed_locguided_dcff_highres_depthaware_v17_selfmap_export_corrwls_probe_extproj_scale025_projected_direct

model:
  direct_featuremetric_use_local_corr_projection: true
  feature_select_use_local_corr_projection: true
