base_config: concat_loc_cambridge_oldhospital_processed_adaptive_v7_locaware_matcher_gru_flowhead_obs_aftertrans0_outer5_v1_short_eval.yaml
exp_name: concat_loc_cambridge_oldhospital_processed_adaptive_v7_locaware_matcher_gru_flowhead_obs_aftertrans0_rot075_outer5_v1_short_eval

model:
  pose_update_rot_scale_after_first: 0.75
