base_config: concat_loc_cambridge_oldhospital_processed_locguided_dcff_highres_depthaware_v17_selfmap_export_corrwls_probe_extproj_scale025.yaml
exp_name: concat_loc_cambridge_oldhospital_processed_locguided_dcff_highres_depthaware_v17_selfmap_export_corrwls_probe_extproj_scale025_v70_localflow

model:
  local_matcher_enabled: true
  local_matcher_hidden_dim: 64
  local_matcher_zero_init: false
  local_matcher_residual_scale: 0.5
  local_matcher_context_mode: basic
  local_matcher_init_checkpoint: /root/ICLPose/result/result/feature_extract/joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v70_localmatcher_flow_from_v68/checkpoints/best.pth

  local_flow_head_enabled: true
  local_flow_head_hidden_dim: 128
  local_flow_head_zero_init: false
  local_flow_head_max_flow: 8.0
  local_flow_head_base_flow_mode: softargmax
  local_flow_head_base_temperature: 0.01
  local_flow_head_context_mode: basic
  local_flow_head_init_checkpoint: /root/ICLPose/result/result/feature_extract/joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v70_localmatcher_flow_from_v68/checkpoints/best.pth
  corr_wls_use_local_flow_head: true
