dataset:
  source_dir: /hy-tmp/Cambridge_stdloc/OldHospital/processed
  colmap_dir: /hy-tmp/Cambridge_stdloc/OldHospital/sparse/0
  feature_dir: /root/ICLPose/result/feature_extract/exported_query/adaptive_v7_stagea_locaware_matcher_v3_highres544_val_colmap
  train_split: /hy-tmp/Cambridge_stdloc/OldHospital/dataset_train.txt
  test_split: /hy-tmp/Cambridge_stdloc/OldHospital/dataset_test.txt
  fine_hw: [544, 960]
  coarse_hw: [34, 60]
  normalize_features: false

dcff:
  checkpoint: /root/ICLPose/result/feature_field/dcff_cambridge_oldhospital_processed_adaptive_bottleneck_v7_finecap_edge_gpu0_b16/checkpoints/best.pth
  ply_path: /root/ICLPose/result/feature_field/dcff_cambridge_oldhospital_processed_adaptive_bottleneck_v7_finecap_edge_gpu0_b16/checkpoints/best.ply
  feature_dim: 96
  fine_feature_dim: 96
  coarse_feature_dim: 32
  latent_dim: 48
  fine_latent_dim: 32
  coarse_latent_dim: 16
  render_width: 960
  render_height: 544
  coarse_smoothing_kernel: 3
