base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v32_flowhead_direct_fast_frozenmap.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v33_flowhead_context_fast_frozenmap

training:
  seed: 443
