base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v55_projected_fm_querymap.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v55_projected_fm_querymap_probe

training:
  epochs: 4
  save_every_epochs: 1
  val_every_epochs: 1
