base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v116_top16_initialsoft_costreg_end2end_from_v74.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v118_top16_initialsoft_costreg_sharp_end2end_from_v74

training:
  seed: 218
  max_steps: 640

map_supervision:
  candidate_score_fusion_target_temperature_m: 0.10
  candidate_score_fusion_cost_regression_temperature_m: 0.10
