base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v44_corr_concat_highpass_selfdistill_finedecoder.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v47_native_concat_highpass_selfdistill_finedecoder

training:
  seed: 593

