base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v40_identitycorr_balanced_unfreezefine.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v41_identitycorr_balanced_finedecoder

training:
  seed: 541
  lr: 0.00002
  batch_size: 2
  max_steps: 700
  freeze_model_except_prefixes:
    - "fine_fuse."
    - "fine_low_fuse."
    - "fine_low_scale"
    - "fine_highres_fuse."
    - "fine_highres_scale"
    - "fine_head."
    - "fine_loc_head."
    - "fine_loc_highres_fuse."
    - "fine_loc_scale"
    - "fine_loc_highres_scale"
