base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v112_top16_calibrated_wlssoft_costreg_pairrank_end2end_from_v74.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v115_top16_calibrated_wlssoft_costreg_contextscore_pairrank_end2end_from_v74

training:
  seed: 215
  max_steps: 640

model:
  candidate_score_map_fusion_context_layers: 1
  candidate_score_map_fusion_context_heads: 2
  candidate_score_map_fusion_context_feedforward_dim: 548
