base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_locdriven_decoupled_flowhead_v15_flowlarge.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_locdriven_decoupled_flowhead_v16_flowdir

training:
  seed: 911
  lr: 0.00008
  max_steps: 500

map_supervision:
  query_corr_flow_weight: 24.0
  query_corr_flow_cosine_weight: 10.0
  query_corr_flow_head_conf_weight: 0.05
  query_corr_min_flow_px: 1.50
  query_corr_max_flow_px: 8.0
  query_corr_huber_delta: 0.12
