base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v74_implicit_joint_pose_energy_from_v68.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v75_implicit_joint_pose_energy_no_teacher_from_v68

training:
  seed: 175

loss:
  fine_l1_weight: 0.0
  fine_cos_weight: 0.0
  fine_grad_weight: 0.0
  fine_channel_std_weight: 0.0
  coarse_l1_weight: 0.0
  coarse_cos_weight: 0.0
  coarse_grad_weight: 0.0
  coarse_channel_std_weight: 0.0
  query_teacher_infonce_weight: 0.0

map_supervision:
  rendered_teacher_fine_weight: 0.0
  rendered_teacher_coarse_weight: 0.0
  coarse_pose_energy_weight: 3.0
  query_coarse_weight: 0.10
  query_coarse_infonce_weight: 0.01
