base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v41_patchonly_frozenmap_overfit.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v42_patchonly_jointmap_overfit

training:
  lr: 0.00006
  max_steps: 300

map_supervision:
  trainable: true
  map_lr_scale: 0.05
  train_fine_decoder: true
  train_feat_sharp: true
  train_fsm: true
  train_hash_mlp: false
  train_latent: false
  train_geometry: false
