base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v122_top16_initialhard_costreg_long_end2end_from_v74.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v125_top16_initialhard_costreg_contextres_from_v122

training:
  seed: 225
  max_steps: 960

model:
  candidate_score_map_fusion_context_layers: 1
  candidate_score_map_fusion_context_heads: 2
  candidate_score_map_fusion_context_feedforward_dim: 548
  candidate_score_map_fusion_context_residual: true
