base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v71_directloc_projected_only.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v72_directloc_projected_identity_softdistill

training:
  seed: 769

map_supervision:
  query_projected_fine_weight: 6.0
  query_identity_corr_distill_weight: 2.0
