base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v101_batchcandidate_corrvolume_wlssoft_calibrated_end2end_top8_from_v74.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v106_top16_calibrated_wlssoft_nostage2_end2end_from_v74

dataset:
  pose_candidate_topk: 16

training:
  seed: 206
  max_steps: 640

map_supervision:
  candidate_render_score_train_map: false
  candidate_render_score_max_candidates: 16
  candidate_stage1_topk: 16
  candidate_two_stage_enabled: false
  candidate_refined_pose_weight: 0.0
