base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v49_varwls_domainadapter_hardpatch.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v50_varwls_inwindow_domainadapter_hardpatch
