base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v64_unified_attn_residual_spatial_fulltrain.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v65_unified_attn_residual_spatial_alignfirst

training:
  seed: 165

map_supervision:
  query_fine_weight: 1.0
  query_coarse_weight: 0.5
  query_fine_infonce_weight: 0.05

  query_corr_ce_weight: 0.0
  query_corr_subpixel_weight: 0.0
  query_corr_peak_margin_weight: 0.0
  query_corr_wls_pose_weight: 0.0
  feature_metric_pose_weight: 0.0
