base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_locdriven_decoupled_corrmatcher_v21_peakce.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_locdriven_decoupled_corrmatcher_v25_wls_from_v21

training:
  seed: 967
  lr: 0.00003
  max_steps: 300
  model_lr_scales:
    local_matcher.: 2.0
    stage3.: 0.01
    stage4.: 0.03
    fine_head.: 0.10
    fine_loc_head.: 2.0
    fine_loc_highres_fuse.: 2.0
    local_corr_projector.: 2.0

map_supervision:
  query_corr_flow_decode_mode: argmax_st
  query_corr_ce_weight: 6.0
  query_corr_subpixel_weight: 2.0
  query_corr_peak_margin_weight: 12.0
  query_corr_wls_pose_weight: 0.3
  query_corr_pose_gain_weight: 0.1
  query_corr_pose_gain_trans_margin_mm: 0.5
  query_corr_pose_gain_rot_margin_deg: 0.01
  query_corr_wls_pose_damping: 0.05
  query_corr_wls_pose_update_scale: 0.20
  query_corr_wls_pose_rot_weight: 0.1
  query_corr_wls_pose_trans_weight: 20.0
  query_corr_wls_conf_threshold: 0.0
  query_corr_wls_conf_power: 2.0
