base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v34_direct_sparse_jointmap_diag300.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v36_direct_sparse_jointmap_splitfix_diag300

