base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v57_stagea_projector_only.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v58_stagea_queryhead_projector

training:
  max_steps: 256
  freeze_model_except_prefixes:
    - local_corr_projector.
    - fine_loc_head.
    - fine_loc_highres_fuse.
  model_lr_scales:
    local_corr_projector.: 8.0
    fine_loc_head.: 4.0
    fine_loc_highres_fuse.: 4.0
