base_config: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v33_direct_sparse_stagea_diag200.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_pca64_depthaware_v35_direct_sparse_stagea_splitfix_diag200

