base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v9_matcher_argmaxst_pretrain.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v10_matcher_argmaxst_wls

training:
  seed: 269
  max_steps: 700

map_supervision:
  query_corr_wls_pose_weight: 0.8
  query_corr_wls_pose_damping: 0.01
  query_corr_wls_pose_update_scale: 1.0
  query_corr_wls_pose_rot_weight: 0.3
  query_corr_wls_pose_trans_weight: 50.0
  query_corr_pose_gain_weight: 2.0
  query_corr_pose_gain_trans_weight: 1.0
