base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_locdriven_coarseinit_fineloc_mapjoint_v1.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_locdriven_coarseinit_fineloc_mapjoint_v2_coarseglobal

pose_init:
  enabled: true
  trans_weight: 0.25
  rot_weight: 0.10
  score_weight: 1.0
  uncertainty_weight: 0.0
  rot_cost_weight: 0.1
  anchor_weight: 5.0

training:
  seed: 823
  lr: 0.00002
  max_steps: 700
  freeze_model_except_prefixes:
    - "stage3."
    - "stage4."
    - "coarse_refine."
    - "coarse_head."
    - "fine_fuse."
    - "fine_low_fuse."
    - "fine_low_scale"
    - "fine_highres_fuse."
    - "fine_highres_scale"
    - "fine_head."
    - "fine_loc_head."
    - "fine_loc_highres_fuse."
    - "fine_loc_scale"
    - "fine_loc_highres_scale"
    - "local_corr_projector."
    - "pose_init_head."
  model_lr_scales:
    pose_init_head.: 5.0
    stage3.: 0.25
    stage4.: 0.50
    coarse_refine.: 2.0
    coarse_head.: 2.0
    local_corr_projector.: 4.0
    fine_loc_head.: 2.0
    fine_loc_highres_fuse.: 2.0

map_supervision:
  query_coarse_weight: 0.12
  coarse_pose_rank_weight: 2.0
  coarse_pose_rank_temperature: 0.05
  query_coarse_infonce_weight: 0.040
  query_coarse_grad_weight: 0.002
