base_config: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v6_matcher_flowpretrain.yaml
exp_name: joint_radio_dcff_cambridge_oldhospital_processed_adaptive_v7_stagea_locaware_flowhead_v7_matcher_softflow

model:
  local_flow_head_enabled: false

training:
  seed: 239
  max_steps: 700

map_supervision:
  local_flow_head_enabled: false
  query_corr_flow_head_conf_weight: 0.0
