base_config: /root/ICLPose/feature_extract/configs/nvs_pose_feature_adapter_stage1_matchingloc_teacherquality_q50_paircorr.yaml
exp_name: nvs_pose_feature_adapter_stage1_matchingloc_teacherquality_q50_paircorr_shuf

dataset:
  train_pose_candidate_cache: /root/ICLPose/result/result/feature_extract/pose_init_exports/oldhospital_local_lattice_renderloftr_q50cm10deg_top16_noexact_train256_shuf20260515.npz
  val_pose_candidate_cache: /root/ICLPose/result/result/feature_extract/pose_init_exports/oldhospital_local_lattice_renderloftr_q50cm10deg_top16_noexact_val128_shuf20260515.npz
