exp_name: dcff_cambridge_oldhospital_processed_cached64_v7_spatial_coarse_stronggrad_4gpu
output_dir: /root/ICLPose/result/feature_field

dataset:
  type: cambridge
  source_dir: /hy-tmp/Cambridge_stdloc/OldHospital
  images: processed
  feature_dir: /root/ICLPose/result/feature_extract/features_radio_dual/cambridge_oldhospital_processed

teacher:
  mode: cached

model:
  sh_degree: 3
  white_background: false
  latent_dim: 64
  fine_latent_dim: 40
  coarse_latent_dim: 24
  feature_dim: 64
  fine_feature_dim: 64
  coarse_feature_dim: 64
  coarse_smoothing_kernel: 1

fine_decoder:
  type: spatial
  hidden_dim: 192
  use_viewdirs: false

coarse_decoder:
  mode: spatial_direct
  carrier_hidden_dim: 192

refiner:
  type: none

hash_grid:
  input_mode: legacy
  n_levels: 16
  n_features_per_level: 2
  log2_hashmap_size: 20
  base_resolution: 16
  max_resolution: 4096
  sh_degree: 3
  mlp_hidden: 256
  mlp_layers: 3
  forward_chunk_size: 32768

training:
  init_ply: /root/ICLPose/result/feature_field/dcff_cambridge_oldhospital_processed_cached64_v6_spatial_coarse_grad_4gpu/checkpoints/best.ply
  warmstart_checkpoint: /root/ICLPose/result/feature_field/dcff_cambridge_oldhospital_processed_cached64_v6_spatial_coarse_grad_4gpu/checkpoints/best.pth
  warmstart_restore_geometry_state: true
  warmstart_restore_coarse_fusion_state: true
  iterations: 3000
  seed: 12345
  freeze_geometry: true
  batch_size: 14
  cache_resized_images: true
  image_cache_dtype: float16

  fine_start_iter: 0
  coarse_start_iter: 0
  warmup_iters: 100
  grad_clip: 0.75
  coarse_downsample: false

  position_lr_init: 0.000005
  position_lr_final: 0.00000005
  feature_lr: 0.0005
  opacity_lr: 0.002
  scaling_lr: 0.0002
  rotation_lr: 0.0001

  latent_lr: 0.0003
  lr_hash_grid: 0.0
  lr_fine_decoder: 0.0002
  lr_coarse_fusion: 0.0009
  lr_refiner: 0.0000

  percent_dense: 0.01
  longest_edge: 640

  log_every: 50
  best_save_every: 250
  save_every: 1000
  val_every: 1000
  sh_degree_up_every: 1000
  use_amp: true

  loss:
    lambda_dssim: 0.2
    lambda_fine_cos: 1.0
    lambda_fine_l1: 1.0
    lambda_coarse_cos: 0.5
    lambda_coarse_l1: 1.0
    lambda_fine_grad: 0.2
    lambda_coarse_grad: 8.0
    lambda_fine_nce: 0.04
    lambda_coarse_nce: 0.12
    nce_temperature: 0.07
    nce_samples: 320
    lambda_tv: 0.0
    lambda_coarse_screen_tv: 0.0
    lambda_normal: 0.0
    lambda_dist: 0.0
    lambda_channel_std: 0.25
