dataset:
  source_dir: /hy-tmp/Cambridge_stdloc/OldHospital
  colmap_dir: /hy-tmp/Cambridge_stdloc/OldHospital/sparse/0
  feature_dir: /root/ICLPose/result/feature_extract/features_radio_dual/cambridge_oldhospital_processed
  train_split: /hy-tmp/Cambridge_stdloc/OldHospital/dataset_train.txt
  test_split: /hy-tmp/Cambridge_stdloc/OldHospital/dataset_test.txt

dcff:
  checkpoint: /root/ICLPose/result/feature_field/dcff_cambridge_oldhospital_processed_cached64_v11_residual_spatial_4gpu/checkpoints/best.pth
  ply_path: /root/ICLPose/result/feature_field/dcff_cambridge_oldhospital_processed_cached64_v11_residual_spatial_4gpu/checkpoints/best.ply
  feature_dim: 64
  fine_feature_dim: 64
  coarse_feature_dim: 64
  latent_dim: 64
  fine_latent_dim: 40
  coarse_latent_dim: 24
  render_width: 120
  render_height: 68
  coarse_smoothing_kernel: 1
  fine_decoder_override:
    type: residual_spatial
    hidden_dim: 224
    num_layers: 5
    use_viewdirs: false
