dataset:
  source_dir: dataset/OldHospital
  colmap_dir: dataset/OldHospital/sparse/0
  train_split: dataset/OldHospital/dataset_train.txt
  test_split: dataset/OldHospital/dataset_test.txt

dcff:
  checkpoint: feature_field/output/dcff_oldhospital_radio_dual_pilot/checkpoints/best.pth
  ply_path: feature_gaussian/output/joint_radio_dual_oldhospital_pilot/point_cloud/iteration_40/point_cloud.ply
  feature_dim: 64
  latent_dim: 32