dataset:
  source_dir: /hy-tmp/Cambridge_stdloc/OldHospital
  colmap_dir: /hy-tmp/Cambridge_stdloc/OldHospital/sparse/0
  train_split: /hy-tmp/Cambridge_stdloc/OldHospital/dataset_train.txt
  test_split: /hy-tmp/Cambridge_stdloc/OldHospital/dataset_test.txt

dcff:
  checkpoint: /root/ICLPose/result/feature_field/dcff_cambridge_oldhospital_processed_adaptive_bottleneck_v7_finecap_edge_gpu0_b16/checkpoints/best.pth
  ply_path: /root/ICLPose/result/feature_field/dcff_cambridge_oldhospital_processed_adaptive_bottleneck_v7_finecap_edge_gpu0_b16/checkpoints/best.ply
  feature_dim: 96
  fine_feature_dim: 96
  coarse_feature_dim: 32
  latent_dim: 48
  fine_latent_dim: 32
  coarse_latent_dim: 16
  render_width: 120
  render_height: 68
  coarse_smoothing_kernel: 3
