exp_name: smoke_dcff_cambridge_oldhospital_nce
output_dir: /root/ICLPose/result/feature_field

dataset:
  type: cambridge
  source_dir: /hy-tmp/Cambridge_stdloc/OldHospital
  images: processed
  feature_dir: /root/ICLPose/result/feature_extract/features_radio_dual/cambridge_oldhospital_processed

teacher:
  mode: cached

model:
  sh_degree: 3
  white_background: false
  latent_dim: 32
  feature_dim: 64
  coarse_smoothing_kernel: 5

fine_decoder:
  type: spatial
  hidden_dim: 64
  use_viewdirs: false

coarse_decoder:
  mode: carrier_residual
  carrier_hidden_dim: 32
  gate_hidden_dim: 32

refiner:
  type: depth_guided
  hidden_dim: 64

hash_grid:
  input_mode: implicit_scale
  scale_dim: 2
  scale_pe_freqs: 2
  include_raw_scale: true
  n_levels: 4
  n_features_per_level: 2
  log2_hashmap_size: 16
  base_resolution: 16
  max_resolution: 256
  mlp_hidden: 64
  mlp_layers: 2

training:
  init_ply: /root/ICLPose/result/feature_gaussian/joint_rgb_geometry_cambridge_oldhospital_processed_rebuild_v2/point_cloud/best/point_cloud.ply
  iterations: 1
  freeze_geometry: true
  batch_size: 2

  fine_start_iter: 0
  coarse_start_iter: 0
  warmup_iters: 1
  grad_clip: 0.75
  coarse_downsample: true

  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001

  latent_lr: 0.0004
  lr_hash_grid: 0.0003
  lr_fine_decoder: 0.0007
  lr_coarse_fusion: 0.0007
  lr_refiner: 0.0007

  percent_dense: 0.01
  densify_from_iter: 999999
  densify_until_iter: 0
  densify_every: 100
  densify_grad_threshold: 0.0002
  min_opacity: 0.005
  max_num_gaussians: 600000
  opacity_reset_every: 999999

  longest_edge: 320

  log_every: 1
  save_every: 999999
  val_every: 0
  sh_degree_up_every: 1000
  use_amp: true

  loss:
    lambda_dssim: 0.2
    lambda_fine_cos: 1.0
    lambda_fine_l1: 1.0
    lambda_coarse_cos: 1.0
    lambda_coarse_l1: 1.0
    lambda_fine_nce: 0.04
    lambda_coarse_nce: 0.04
    nce_temperature: 0.07
    nce_samples: 64
    lambda_tv: 0.01
    lambda_coarse_screen_tv: 0.05
    lambda_normal: 0.0
    lambda_dist: 0.0
    lambda_channel_std: 0.1
